gText_PikachuFollower_BikeShop::
	.string "PIKACHU seems very interested in\nthe bicycles.$"

gText_PikachuFollower_VictoryRoad::
	.string "PIKACHU focused with a sharp\ngaze!$"

gText_PikachuFollower_Rain::
	.string "PIKACHU seems to be happy about\nthe rain!$"

gText_PikachuFollower_Water::
	.string "Waah! PIKACHU suddenly splashed\nwater!$"

gText_PikachuFollower_Sand::
	.string "PIKACHU is blowing sand in the\nair!$"

gText_PikachuFollower_Grass::
	.string "PIKACHU is playing around,\nplucking bits of grass.$"

gText_PikachuFollower_Ice::
	.string "PIKACHU seems surprised to\ntouch ice.$"

gText_PikachuFollower_Happy::
	.string "PIKACHU looks very happy.$"

gText_PikachuFollower_Joy::
	.string "PIKACHU is jumping for joy!$"

gText_PikachuFollower_Cuddle::
	.string "PIKACHU is happily cuddling up\nto you!$"

gText_PikachuFollower_Guard::
	.string "PIKACHU is standing guard.$"

gText_PikachuFollower_Patient::
	.string "PIKACHU is staring patiently at\nnothing at all.$"

gText_PikachuFollower_Relaxing::
	.string "PIKACHU is relaxing comfortably.$"

gText_PikachuFollower_Adoration::
	.string "PIKACHU is regarding you with\nadoration!$"

gText_PikachuFollower_Unhappy::
	.string "PIKACHU seems unhappy somehow…$"

EventScript_PikachuFollower_BikeShop::
	lock
	faceplayer
	msgbox gText_PikachuFollower_BikeShop
	release
	end

EventScript_PikachuFollower_VictoryRoad::
	lock
	faceplayer
	msgbox gText_PikachuFollower_VictoryRoad
	release
	end

EventScript_PikachuFollower_Rain::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Rain
	release
	end

EventScript_PikachuFollower_Water::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Water
	release
	end

EventScript_PikachuFollower_Sand::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Sand
	release
	end

EventScript_PikachuFollower_Grass::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Grass
	release
	end

EventScript_PikachuFollower_Ice::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Ice
	release
	end

EventScript_PikachuFollower_Happy::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Happy
	release
	end

EventScript_PikachuFollower_Joy::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Joy
	release
	end

EventScript_PikachuFollower_Cuddle::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Cuddle
	release
	end

EventScript_PikachuFollower_Guard::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Guard
	release
	end

EventScript_PikachuFollower_Patient::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Patient
	release
	end

EventScript_PikachuFollower_Relaxing::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Relaxing
	release
	end

EventScript_PikachuFollower_Adoration::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Adoration
	release
	end

EventScript_PikachuFollower_Unhappy::
	lock
	faceplayer
	msgbox gText_PikachuFollower_Unhappy
	release
	end
